### ISSUE TITLE
Random Acts Page - User Story 7

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_web#19]
## Feature: Random Acts Page

As a visitor,/logged-in user, when I visit the random acts page “/random_acts”,

- [X]   I see 3 deed names; each deed is a link

## Navigation: 
   Links: "Deed 1", "Deed 2", "Deed 3"

**As a logged-in user**
When I click one of the deeds:

- [X] I am redirected to the new good deed page -> "/user/good_deeds/new"

**Comment by MelTravelz** [comment]
**Update Needed:** 

- the redirect changed to `new good deed form`
