### ISSUE TITLE
Home Page - User Story 1

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_web#3]
## Feature: Home Page

As a visitor, when I visit the home page “/”,

- [ ]   I see the Title of the App, with its moto/logo
- [ ]   I see a header "DO GOOD" that links to the home page (this is on every page of the website)
- [ ]   I see a feed of images with hashtags/name of good deed of all completed Good Deed activities
- [ ]   I see a button to "Login/Register"

## Navigation: 
   Links: "DO GOOD" & "Login/Register"

When I click the "Login/Register" link,

- [ ] I am taken to the login page"/login" where I see a link to login with Google

When I click the "DO GOOD" link,

- [ ] I am taken to the home page "/"

**Comment by MelTravelz** [comment]
**Updates Needed:**

- Button name & route changed for button from "Get Random Acts` to `"Login/Register"`
- Consider changing `hashtags` to `the name of the good deed`
