### ISSUE TITLE
Header for all other pages - User Story 3

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_web#5]
## Navigation:
 
As a logged in user, when I visit a page besides home & login pages,

- [ ] I see a header with links to `Home`, `My Page`, `Logout`

When I click on the `Home` link,

- [ ] I am redirected to the home page "/"

When I click on the `My Page` link,

- [ ] I am redirected to my user show page "/dashboard"

When I click on the `Log Out` link,

- [ ] I am redirected to the home page "/"
- [ ] I see a message, "Successfully logged out"

**Comment by MelTravelz** [comment]
- UPDATE: there is now NO login/register link in the header (that has been moved into a button and is functioning)
- Clicking on the"Home" link has been tested in this file: `spec/features/homepage/index_spec.rb`
- Also, do we want "sticky" header vs "sticky" footer? If yes, then we'll need to figure out how to ensure the footer stays at the bottom of shorter pages (like the random acts page)
