### ISSUE TITLE
Register Page (from Home/Login) - User Story 5

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_web#7]
## Feature: Register Page
As a visitor, when I visit the register page “/login”,

- [ ] I see a form with fields to enter:
        -Name
        -Email
        -Password
        -Password confirmation
- [ ] I see a submit button
- [ ] I see a button "Register with Google"

## Navigation:
Buttons: "Register", "Register with Google"

**When entering register page from home page/ login page**

When I enter all my information, and click the Register button,

- [ ] I am redirected to the home page
- [ ] I see a message, "Welcome, <name>!"

## Sad Path:

If I leave some or all fields blank and click register,

- [ ] I am redirected to the register page
- [ ] I see an error message

**Comment by MelTravelz** [comment]
As per our discussion, it appears we might not need an individual register page since Google OAuth will login OR create a new user
